# Generated by Django 5.1.4 on 2024-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_video_url_coursesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="image",
            field=models.ImageField(
                default="https://www.google.com/imgres?q=html%20course%20banner%20filetype%3A%20png&imgurl=https%3A%2F%2Fd1jnx9ba8s6j9r.cloudfront.net%2Fimgver.1551437392%2Fimg%2Fco_img_1518_1631724053.png&imgrefurl=https%3A%2F%2Fwww.edureka.co%2Fhtml-certification-course&docid=i5n6bPQlMDy07M&tbnid=x7JAorop62XXXM&vet=12ahUKEwiGnsa9sseKAxWw_rsIHfd-NEkQM3oECFQQAA..i&w=355&h=189&hcb=2&ved=2ahUKEwiGnsa9sseKAxWw_rsIHfd-NEkQM3oECFQQAA",
                upload_to="category/",
            ),
            preserve_default=False,
        ),
    ]
