# Generated by Django 5.1.4 on 2024-12-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default=11, upload_to="course/"),
            preserve_default=False,
        ),
    ]
