# Generated by Django 5.1.4 on 2024-12-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesession",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="courses.course",
            ),
        ),
    ]
